[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "picogen"
version = "0.0.1"
description = "Tiny statis website generator."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4 == 4.12.3",
    "Jinja2 == 3.1.4",
    "Markdown == 3.6",
    "python-dotenv == 1.0.1",
    "python-slugify == 8.0.4",
]

[project.scripts]
picogen-build = "picogen.__main__:build"

[project.urls]
"Homepage" = "https://github.com/vlatan/picogen"
